dvb-core/dmxdev: Ensure ctx is a valid variable
When enabling CONFIG_DVB_MMAP the dvb_vb2_ctx is copied to a
non-existant variable ctx, which causes an obvious compilation error.

dvb-core/dmxdev.c: In function ‘dvb_dmxdev_ts_callback’:
dvb-core/dmxdev.c:495:17: error: ‘ctx’ undeclared (first use in this function)
  495 |                 ctx = &dmxdevfilter->vb2_ctx;
      |                 ^~~
dvb-core/dmxdev.c:495:17: note: each undeclared identifier is reported only once for each function it appears in

This was fixed upstream in commit 57868acc369a (media: videobuf2: Add new uAPI
for DVB streaming I/O, Mon Dec 18 22:35:53 2017 -0500) about 5 years
ago.

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>