ddbridge/main: Remove `pci_set_dma_mask`
Starting with Linux 5.18 `pci_set_dma_mask` has been removed. This patch
mimics commit 887069f42455 (media: switch from 'pci_' to 'dma_' API, Sun
Aug 22 11:30:08 2021 +0200) from upstream and thus prevents the
following compilation error.

ddbridge/ddbridge-main.c: In function ‘ddb_probe’:
ddbridge/ddbridge-main.c:286:14: error: implicit declaration of function ‘pci_set_dma_mask’; did you mean ‘ipi_send_mask’? [-Werror=implicit-function-declaration]
  286 |         if (!pci_set_dma_mask(pdev, DMA_BIT_MASK(64))) {
      |              ^~~~~~~~~~~~~~~~
      |              ipi_send_mask
ddbridge/ddbridge-main.c:287:17: error: implicit declaration of function ‘pci_set_consistent_dma_mask’ [-Werror=implicit-function-declaration]
  287 |                 pci_set_consistent_dma_mask(pdev, DMA_BIT_MASK(64));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>